version: '3.9'
services:
    database:
        image: postgres:15
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
    app:
        image: openjdk:17
        volumes:
            - ./target/project-0.3.jar:/app.jar
            - ./src/main/resources/app/databases/taxonomy_iw.csv:/data.csv
            - ./config/postgres.config:/postgres.config
        depends_on:
            - database
        command: "java -jar app.jar"
        stdin_open: true
        tty: true